// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: exchanger.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyExchanger_GetExchangeRate_FullMethodName = "/proto.CurrencyExchanger/GetExchangeRate"
	CurrencyExchanger_ConvertCurrency_FullMethodName = "/proto.CurrencyExchanger/ConvertCurrency"
)

// CurrencyExchangerClient is the client API for CurrencyExchanger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyExchangerClient interface {
	GetExchangeRate(ctx context.Context, in *ExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error)
	ConvertCurrency(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
}

type currencyExchangerClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyExchangerClient(cc grpc.ClientConnInterface) CurrencyExchangerClient {
	return &currencyExchangerClient{cc}
}

func (c *currencyExchangerClient) GetExchangeRate(ctx context.Context, in *ExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeRateResponse)
	err := c.cc.Invoke(ctx, CurrencyExchanger_GetExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyExchangerClient) ConvertCurrency(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertResponse)
	err := c.cc.Invoke(ctx, CurrencyExchanger_ConvertCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyExchangerServer is the server API for CurrencyExchanger service.
// All implementations must embed UnimplementedCurrencyExchangerServer
// for forward compatibility.
type CurrencyExchangerServer interface {
	GetExchangeRate(context.Context, *ExchangeRateRequest) (*ExchangeRateResponse, error)
	ConvertCurrency(context.Context, *ConvertRequest) (*ConvertResponse, error)
	mustEmbedUnimplementedCurrencyExchangerServer()
}

// UnimplementedCurrencyExchangerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyExchangerServer struct{}

func (UnimplementedCurrencyExchangerServer) GetExchangeRate(context.Context, *ExchangeRateRequest) (*ExchangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (UnimplementedCurrencyExchangerServer) ConvertCurrency(context.Context, *ConvertRequest) (*ConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertCurrency not implemented")
}
func (UnimplementedCurrencyExchangerServer) mustEmbedUnimplementedCurrencyExchangerServer() {}
func (UnimplementedCurrencyExchangerServer) testEmbeddedByValue()                           {}

// UnsafeCurrencyExchangerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyExchangerServer will
// result in compilation errors.
type UnsafeCurrencyExchangerServer interface {
	mustEmbedUnimplementedCurrencyExchangerServer()
}

func RegisterCurrencyExchangerServer(s grpc.ServiceRegistrar, srv CurrencyExchangerServer) {
	// If the following call pancis, it indicates UnimplementedCurrencyExchangerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyExchanger_ServiceDesc, srv)
}

func _CurrencyExchanger_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyExchangerServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyExchanger_GetExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyExchangerServer).GetExchangeRate(ctx, req.(*ExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyExchanger_ConvertCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyExchangerServer).ConvertCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyExchanger_ConvertCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyExchangerServer).ConvertCurrency(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyExchanger_ServiceDesc is the grpc.ServiceDesc for CurrencyExchanger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyExchanger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CurrencyExchanger",
	HandlerType: (*CurrencyExchangerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeRate",
			Handler:    _CurrencyExchanger_GetExchangeRate_Handler,
		},
		{
			MethodName: "ConvertCurrency",
			Handler:    _CurrencyExchanger_ConvertCurrency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchanger.proto",
}
